name: Node CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        node-version: [10.19.0, 11.15.0, 12.16.1]
        os: [ubuntu-16.04, ubuntu-18.04, windows-2019, macos-10.15]

    name: Build for platform ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install NPM packages
      run: npm install
    - name: Build
      run: npm run build 
      env:
        CI: true
    - uses: actions/upload-artifact@v1
      with:
        name: cmus-discord-rpc-bin_${{ matrix.os }}_node-${{ matrix.node-version }}
        path: dist/
        
